name: Build RuoYi-admin Module

    # 触发条件：当RuoYi-admin目录下有代码提交时触发
    on:
      push:
        paths:
          - 'RuoYi-admin/**'
      pull_request:
        paths:
          - 'RuoYi-admin/**'

    jobs:
      build:
        # 在Ubuntu最新版本上运行
        runs-on: ubuntu-latest

        steps:
          # 检出代码仓库
          - name: Checkout code
            uses: actions/checkout@v4

          # 设置Java 21环境
          - name: Set up JDK 21
            uses: actions/setup-java@v4
            with:
              java-version: '21'
              distribution: 'temurin'
              cache: maven

          # 打包RuoYi-admin目录下的ruoyi-admin模块，跳过测试
          - name: Build ruoyi-admin module
            working-directory: ./RuoYi-admin/ruoyi-admin
            run: mvn clean package -DskipTests

          # 上传打包产物（可选步骤）
          - name: Upload build artifact
            uses: actions/upload-artifact@v4
            with:
              name: ruoyi-admin-build
              path: RuoYi-admin/ruoyi-admin/target/*.jar
    
