name: RuoYi-admin 自动打包

# 触发条件：仅当RuoYi-admin目录或工作流文件变更时触发
on:
  push:
    branches: [ "main" ]
    paths:
      - 'RuoYi-admin/**'
      - '.github/workflows/auto-package-ruoyi-admin.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'RuoYi-admin/**'
      - '.github/workflows/auto-package-ruoyi-admin.yml'

jobs:
  build-and-package:
    runs-on: ubuntu-latest

    steps:
    - name: 拉取代码
      uses: actions/checkout@v4

    - name: 配置 JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        # 针对RuoYi-admin目录的pom.xml缓存依赖
        cache-dependency-path: RuoYi-admin/pom.xml

    - name: 构建并测试RuoYi-admin项目
      working-directory: ./RuoYi-admin
      run: mvn -B clean verify

    - name: 打包RuoYi-admin为JAR
      working-directory: ./RuoYi-admin
      run: mvn -B package -DskipTests

    - name: 保存打包产物
      uses: actions/upload-artifact@v4
      with:
        name: ruoyi-admin-app-${{ github.sha }}
        path: RuoYi-admin/target/*.jar
        retention-days: 30

