name: Build RuoYi-admin (Multi-module)

on:
  push:
    paths:
      - 'RuoYi-admin/**'
  pull_request:
    paths:
      - 'RuoYi-admin/**'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install tree (for directory inspection)
        run: sudo apt-get install -y tree
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      
      - name: Show project structure
        working-directory: ./RuoYi-admin
        run: |
          echo "Project structure (RuoYi-admin root):"
          tree -L 4  # 显示4级目录，便于查看子模块结构
      
      - name: Build all modules with Maven
        working-directory: ./RuoYi-admin
        run: |
          # 从父模块构建所有子模块
          mvn clean package -DskipTests
          # 查看构建结果摘要
          echo "Build summary:"
          mvn help:evaluate -Dexpression=project.modules | grep -v "\[INFO\]"
      
      - name: Find submodule jar files
        id: find_jars
        working-directory: ./RuoYi-admin
        run: |
          # 查找所有子模块中的jar文件，排除测试相关和父模块（pom）
          echo "Found jar files in submodules:"
          find . -type f -name "*.jar" \
            -not -path "*/target/test-classes/*" \
            -not -path "*/target/*-tests.jar"
          
          # 保存jar文件路径到环境变量
          echo "JAR_PATHS=$(find . -type f -name "*.jar" \
            -not -path "*/target/test-classes/*" \
            -not -path "*/target/*-tests.jar" | tr '\n' ' ')" >> $GITHUB_ENV
      
      - name: List found jar files
        if: env.JAR_PATHS != ''
        working-directory: ./RuoYi-admin
        run: |
          echo "Jar files to be uploaded:"
          echo $JAR_PATHS | tr ' ' '\n'
      
      - name: Upload build artifacts
        if: env.JAR_PATHS != ''
        uses: actions/upload-artifact@v4
        with:
          name: ruoyi-admin-submodules-build
          path: |
            ${{ env.JAR_PATHS }}
      
      - name: Handle missing jars
        if: env.JAR_PATHS == ''
        run: |
          echo "Warning: No jar files found in submodules"
          echo "Check Maven build logs for possible errors"
          # 可选：如果希望构建失败，取消下面这行的注释
          # exit 1
