name: Build RuoYi-admin (Dynamic Modules)

on:
  push:
    paths:
      - 'RuoYi-admin/**'
  pull_request:
    paths:
      - 'RuoYi-admin/**'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install tree
        run: sudo apt-get install -y tree
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      
      - name: Show project structure
        working-directory: ./RuoYi-admin
        run: tree -L 4
      
      - name: Build all modules with Maven
        working-directory: ./RuoYi-admin
        run: mvn clean package -DskipTests
      
      - name: Find submodules and jar files
        id: find_modules
        working-directory: ./RuoYi-admin
        run: |
          # 从父pom.xml中提取所有子模块
          echo "Extracting modules from parent pom.xml..."
          mvn help:evaluate -Dexpression=project.modules | grep -v "\[INFO\]" | grep -v "^$" > modules.txt
          
          echo "Found submodules:"
          cat modules.txt
          
          # 为每个模块生成jar路径模式
          echo "Generating jar path patterns..."
          > jar_patterns.txt
          while IFS= read -r module; do
            # 每个模块的jar路径模式
            echo "${{ github.workspace }}/RuoYi-admin/$module/target/*.jar" >> jar_patterns.txt
            echo "${{ github.workspace }}/RuoYi-admin/$module/target/*/*.jar" >> jar_patterns.txt
          done < modules.txt
          
          # 显示生成的路径模式
          echo "Generated jar path patterns:"
          cat jar_patterns.txt
          
          # 将路径模式转换为GitHub Actions的多行格式
          patterns=$(cat jar_patterns.txt | tr '\n' '|' | sed 's/|$//')
          echo "PATTERNS=$patterns" >> $GITHUB_ENV
          
          # 检查是否有模块
          if [ -s modules.txt ]; then
            echo "HAS_MODULES=true" >> $GITHUB_ENV
          else
            echo "HAS_MODULES=false" >> $GITHUB_ENV
          fi
      
      - name: List all found jar files
        if: env.HAS_MODULES == 'true'
        working-directory: ./RuoYi-admin
        run: |
          echo "All jar files found in modules:"
          while IFS= read -r pattern; do
            echo "Searching in: $pattern"
            find $(dirname "$pattern") -maxdepth 1 -name "$(basename "$pattern")"
          done < jar_patterns.txt
      
      - name: Upload build artifacts
        if: env.HAS_MODULES == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: ruoyi-admin-modules-build
          path: |
            ${{ env.PATTERNS }}
      
      - name: Handle no modules found
        if: env.HAS_MODULES == 'false'
        run: |
          echo "Error: No submodules found in parent pom.xml"
          exit 1
