name: RuoYi-admin 自动打包（修复版）

on:
  push:
    branches: [ "main" ]
    paths:
      - 'RuoYi-admin/**'
      - '.github/workflows/auto-package-ruoyi-admin.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'RuoYi-admin/**'
      - '.github/workflows/auto-package-ruoyi-admin.yml'

jobs:
  build-and-package:
    runs-on: ubuntu-latest

    steps:
    - name: 拉取代码
      uses: actions/checkout@v4

    - name: 配置 JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        cache-dependency-path: RuoYi-admin/pom.xml

    - name: 查看项目结构（调试用）
      run: |
        echo "当前目录结构："
        ls -l
        echo "RuoYi-admin目录内容："
        ls -l RuoYi-admin/

    - name: 构建并打包（带详细日志）
      working-directory: ./RuoYi-admin
      run: |
        echo "开始构建项目..."
        mvn -X clean package -DskipTests  # -X 输出详细日志，便于排查错误
        echo "构建完成，查看target目录："
        ls -l target/  # 显示target目录内容，确认是否生成JAR

    - name: 保存打包产物
      uses: actions/upload-artifact@v4
      with:
        name: ruoyi-admin-app-${{ github.sha }}
        # 尝试匹配可能的JAR路径（多模块项目常用）
        path: |
          RuoYi-admin/target/*.jar
          RuoYi-admin/**/target/*.jar  # 适配子模块结构
        retention-days: 30
