name: 打包 RuoYi-vue3 生产版本

permissions:
  contents: write

on:
  push:
    branches: [ "main" ]
    paths:
      - 'RuoYi-vue3/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'RuoYi-vue3/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 拉取代码
      uses: actions/checkout@v3

    - name: 设置 Node.js 环境
      uses: actions/setup-node@v3
      with:
        node-version: '22'
        cache: 'yarn'
        # 指定yarn.lock的实际路径
        cache-dependency-path: './RuoYi-vue3/yarn.lock'

    - name: 安装依赖
      working-directory: ./RuoYi-vue3
      run: yarn install --frozen-lockfile  # 现在可以安全使用lockfile选项了

    - name: 执行打包命令
      working-directory: ./RuoYi-vue3
      run: yarn build:prod

    - name: 复制dist目录到deploy
      run: |
        mkdir -p ./deploy/dist
        cp -r ./RuoYi-vue3/dist/* ./deploy/dist/

    - name: 删除打包产物
      run: |
        if [ -d "./RuoYi-vue3/dist" ]; then
          rm -rf ./RuoYi-vue3/dist
          echo "已删除打包产物"
        else
          echo "打包产物目录不存在，无需删除"
        fi

    - name: 提交部署文件
      if: github.event_name == 'push'
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add ./deploy
        CURRENT_TIME=$(TZ='Asia/Shanghai' date +"%Y-%m-%d %H:%M:%S")
        git commit -m "ci(package): ${CURRENT_TIME} upload ruoyi-vue3 dist to root deploy folder" || echo "没有需要提交的更改"
        git push
